name: Pengeek-PL

on:
  workflow_dispatch:
  push:
    branches: [ PL ]
    tags: [ 26 ]
  pull_request:
  merge_group:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'gradle'

    - name: Write key
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/PL' || github.event_name == 'workflow_dispatch')
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
        echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> ../keystore.properties
        echo releaseKeyAlias='${{ secrets.ALIAS }}' >> ../keystore.properties
        echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> ../keystore.properties
        echo releaseStoreFile='key.jks' >> ../keystore.properties
        echo ${{ secrets.SIGNING_KEY }} | base64 --decode > app/key.jks
        else
        touch ../keystore.properties
        fi

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Patch Ninja for C++20 Modules
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        SYSTEM_NINJA=$(which ninja)
        SDK_NINJA="/usr/local/lib/android/sdk/cmake/3.31.5/bin/ninja"
        sudo cp "$SYSTEM_NINJA" "$SDK_NINJA"
        sudo chmod +x "$SDK_NINJA"
        echo "Ninja patched successfully."

    - name: Build with Gradle
      run: ./gradlew assembleRelease assembleDebug -Dorg.gradle.jvmargs="-Xmx4g" --no-daemon

    - name: Rename apk
      run: |
        mkdir -p app/build/outputs/apk/release
        mkdir -p app/build/outputs/apk/debug
        mv app/build/outputs/apk/release/*.apk app/build/outputs/apk/release/Pengeek-PL-release.apk || true
        mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/Pengeek-PL-debug.apk || true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: app/build/outputs/apk

    - name: Upload to Releases
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/PL' || github.event_name == 'workflow_dispatch')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/release/Pengeek-PL-release.apk,app/build/outputs/apk/debug/Pengeek-PL-debug.apk"
        tag: "26"
        name: "Pengeek-PL"
        allowUpdates: "true"
        token: "${{ secrets.GITHUB_TOKEN }}"